name = "spin-mama-app-org"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spin-mama-app.org"
HMAC_KEY = "14e493b97e101da465184d2ce5cbe039359c954a0c3bb008738a6fae9a44eb3c"
COOKIE_NAME = "wj8"
PLAY_PATH = "explore"
BUTTON_ID = "p0c533cdb874e581373d18bb8cf0bdf51"
GATE_SALT = "44affb3392e07d3f"
